### PR TITLE
Fix/org choices

### LINKED ISSUE #26: Organization selection choices
> I am only seeing two orgs but I am in more orgs that that, how are they chosen?

Orgs to select for editing come from the below method currently

https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#list-organizations-for-the-authenticated-user

```ts
public async getGitHubUserOrgs(): Promise<string[]> {
    const octokit = await this.getOctokit();
    const response = await octokit.rest.orgs.listForAuthenticatedUser();
    return response.data.map((org: { login: string }) => org.login);
  }
```

1. Who is using this installer? I'd assume a redirect after https://github.com/ubiquity-os/ubiquity-os-kernel/issues/171 is complete to the installer UI which would naturally be the owner of the org. Then potentially who after that? Admin & Owner? Partner defined?

2. What orgs should be shown when a partner uses the installer?

- Orgs that they are an admin of or just owner of, collaborator of?
- Should the partner determine which roles can edit the config or do we enforce rules, if we enforce then what should they be?

We sort of scrapped global config variables from `ubiquity-os-config.yml` but we could leverage that to enforce partner defined roles which can edit (at least via the UI). 

E.g: The org owner must use it after `kernel-setup` and we allow them to input roles that can edit and we write this to the config separate from `plugins:` and we read this on fetch and check against our authenticated user.

_Originally posted by @Keyrxng in https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/25#issuecomment-2493797026_

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves #26
Requires #25 

Changes:

1. `rest.users.getAuthenticated()`
2. `rest.orgs.listForAuthenticatedUser()`
3. `rest.orgs.listForUser(username)`
4. `rest.repos.getCollaboratorPermissionLevel(org, .ubiquity-os)`

QA:

image

Console:

image

Else:

> (4) ['ubq-testing', 'ubiquity', 'ubiquibot', 'ubiquity-os']

I tried every `.rest.org` method that seemed relevant and none of them returned `-marketplace` for me so idk if that's a me problem or an org problem but it should be fetched at least and either errored in the console or displayed but it's neither. It also didn't display for you either @gentlementlegen and we are both public members of the org.

Could you try to see if `-marketplace` shows up for you now with this change?

### CODE REVIEW

**Comment by gentlementlegen** [comment]
@Keyrxng Could we have preview deployments like we have for other frontend projects?

**Comment by gentlementlegen** [comment]
The orgs show up properly on my side
image

## Bug list

- When you maintain a click on the set defaults, here it what happens
image

- You can click and infinite amount of times on the "add" button
image

- the toast asking you if you want to save disappear even when hovered
- it set the value to "undefined" for OpenAiBaseUrl which I don't think is the desired behavior

**Comment by Keyrxng** [comment]
> The orgs show up properly on my side

Okay that's fine then ty

> When you maintain a click on the set defaults, here it what happens

Will address that

> You can click and infinite amount of times on the "add" button

If you clicked add but made a mistake/wanted to change a param, you'd want to be able to click add again yeah? But otherwise it should only allow you to click add once?

1. user clicks `add`/`remove` > user clicks `push to github` > A) render `pluginSelector` B) disable `add`/`remove`
2. user clicks `add`/`remove` > user closes the notification or it disappears > do nothing

> the toast asking you if you want to save disappear even when hovered

1. It should not disappear at all and requires the user to close or push?
2. If hovered, do not disappear else disappear?

> it set the value to "undefined" for OpenAiBaseUrl which I don't think is the desired behavior
Will address that

**Comment by Keyrxng** [comment]
@gentlementlegen 

Is the preferred behaviour to be this:
image

or for the prop to not be included in the config?

**Comment by gentlementlegen** [comment]
@Keyrxng Not to be included so the default value is used on `Decode` call. If set to an empty string the value then would be `""` not the default.

**Comment by Keyrxng** [comment]
> > the toast asking you if you want to save disappear even when hovered

> If hovered, do not disappear else disappear?

Implemented

> > When you maintain a click on the set defaults, here it what happens

> Will address that

Addressed

> user clicks add/remove > user clicks push to github > A) render pluginSelector B) disable add/remove

Implemented:

- user clicks add/remove > user closes the notification or it disappears > do nothing
- user clicks add/remove > user clicks push to github > render `pluginSelector`


I'm unsure how you want me to handle multiple `add` clicks prior to `push`, please lmk if I should use another approach. Perhaps updating the values directly from input change and refactoring `add` into the push event and removing the notification as one alt? If you could create a new task for it that would be ideal as it'll involve a bit of work, ty.

**Comment by Keyrxng** [comment]
@zugdev fancy doing a review bud?

**Review by rndquu — CHANGES_REQUESTED** [review]
Getting 3 out of 4 expected organizations:
Screenshot 2024-11-29 at 19 09 30

The only missing org is https://github.com/rndquu-org where my account is an owner. It used to be displayed in the previous PRs but this PR somehow doesn't display it.

Pls fix.

**Comment by Keyrxng** [comment]
> The only missing org is https://github.com/rndquu-org where my account is an owner. It used to be displayed in the previous PRs but this PR somehow doesn't display it.

@rndquu your membership is private so it would only be returned by `listForAuthenticatedUser`, can you confirm that it returns it from that call pls? Just like how `-marketplace` doesn't appear anywhere for me but it's showing up for @gentlementlegen makes me believe that it can be settings related which is almost out of our control when considering arbitrary partner orgs.

Perhaps it's the `permission === "write"` check or something I'm not sure, but it's difficult for me to debug your conditions

**Comment by rndquu** [comment]
> @rndquu your membership is private so it would only be returned by `listForAuthenticatedUser`

The missing https://github.com/rndquu-org is displayed in [this](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/23) PR, so it's smth code related.

**Comment by Keyrxng** [comment]
Ty for the clarification I will look into it

**Comment by Keyrxng** [comment]
I expect the issue stems from your org not having a config repo, which we rely on to identify permissions to work around OAuth errors with org settings. I duplicated the logic [here](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/23).

This approach:
- Returns all orgs from `listForAuthenticatedUser`.
- Includes publicly fetched orgs that have a `.ubiquity-os` repo to check permissions.

An alternative would be to list all org repos and check any repo if `.ubiquity-os` does not exist. Let me know which approach you'd prefer.

Hopefully this has resolved it for you, again it's hard for me to debug your conditions locally so my apologies for the back and forth

**Comment by zugdev** [comment]
I think the previous push toaster should disappear if I press on add again

**Comment by zugdev** [comment]
This doesnt change anything for me, so not sure

**Review by rndquu — APPROVED** [review]
Works fine, 4 out of 4 organizations are displayed for me, as expected

**Pull request merged**
