### PR TITLE
Feat/repo select

### LINKED ISSUE #20: Allow selecting individual repository
Depends on https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/13

RIght now partner is able to select only an organization where the bot' config should be edited.

Partner should be able to add/edit config either for an organization either for an individual repository.

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/20
Requires #13 

QA:

https://github.com/user-attachments/assets/1334b3e1-927b-462e-9c38-9fa6db8fde05

### CODE REVIEW

**Comment by Keyrxng** [comment]
@zugdev ready for review bud

**Comment by Keyrxng** [comment]
This is ready but let's wait for #25 first

**Comment by zugdev** [comment]
Is this a subset of commits in #25?

**Comment by Keyrxng** [comment]
@zugdev technically, this was branched off from https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/13 but I haven't pulled main in yet and it'll be cleaner pulling #25 into here than the opposite I think

**Comment by Keyrxng** [comment]
https://github.com/user-attachments/assets/14aa9bab-6e27-42ed-9bbf-018435c67438

**Review by rndquu — CHANGES_REQUESTED** [review]
> Partner should be able to add/edit config either for an organization either for an individual repository.

As far as I understand right now a new partner (which doesn't have the `.ubiquity-os` repository for organization wide config) can not create a config for a whole organization. It should be possible.

**Comment by Keyrxng** [comment]
> > Partner should be able to add/edit config either for an organization either for an individual repository.
> 
> As far as I understand right now a new partner (which doesn't have the `.ubiquity-os` repository for organization wide config) can not create a config for a whole organization. It should be possible.

Resolved. I did have it pre-merge but I mistakenly removed it during merge and I didn't catch it last night I was tired when I pulled into these PRs and didn't work on them beyond that, apologies.

QA: https://github.com/ubq-testing/bot-ai/blob/main/.github/.ubiquity-os.config.yml

**Review by rndquu — APPROVED** [review]
Works fine

**Pull request merged**
